baseURL = 'https://l-hexagraphe.netlify.app/'
languageCode = 'fr-fr'
title = "L'Hexagraphe"
theme = 'ananke'

# Indique au thème Ananke d'utiliser ton fichier CSS personnalisé
[params]
  custom_css = ["css/style.css"]

[[menu.main]]
    name = "Chroniques"
    url = "/chroniques/"
    weight = 1

[[menu.main]]
    name = "L'Univers"
    url = "/univers/"
    weight = 2
[permalinks]
  chroniques = '/chroniques/:slug/'