baseURL = 'https://l-hexagraphe.netlify.app/'
languageCode = 'fr-fr'
title = "L'Hexagraphe"
theme = 'ananke'

# Supprime l'ancien bloc [staticDir] et mets juste ça si tu veux le préciser :
staticDir = ['static']

[[menu.main]]
    name = "Chroniques"
    url = "/chroniques/"
    weight = 1