collections:
  - name: "chroniques"         # On change 'blog' en 'chroniques'
    label: "Articles de JDR"
    folder: "content/chroniques" # On pointe vers ton nouveau dossier
    create: true
    slug: "{{slug}}"           # Plus simple pour les URLs
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Corps du texte", name: "body", widget: "markdown"}