backend:
  name: git-gateway
  branch: main
  identity_url: "https://l-hexagraphe.netlify.app/.netlify/identity"
  gateway_url: "https://l-hexagraphe.netlify.app/.netlify/git"

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Articles de JDR"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Corps du texte", name: "body", widget: "markdown"}